apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: splitter

resources:
  - ../../template

patches:
  - target:
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: splitter
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: splitter

images:
  - name: template
    newName: historical-date-split-worker
