apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: database
spec:
  members: 1
  type: ReplicaSet
  version: latest
  security:
    authentication:
      modes: ["SCRAM"]
  users: []
  #   - name: my-user
  #     db: admin
  #     passwordSecretRef: # a reference to the secret that will be used to generate the user's password
  #       name: my-user-password
  #     roles:
  #       - name: clusterAdmin
  #         db: admin
  #       - name: userAdminAnyDatabase
  #         db: admin
  #     scramCredentialsSecretName: my-scram
  # additionalMongodConfig:
  #   storage.wiredTiger.engineConfig.journalCompressor: zlib
